name: (all packages) Lints
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # needed for pre-commit to work correctly
      - name: Install Nix
        uses: cachix/install-nix-action@fc6e360bedc9ee72d75e701397f0bb30dce77568 # v31.5.2
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run pre-commit checks
        run: |
          nix develop -c sh -c "pre-commit run --hook-stage pre-commit --show-diff-on-failure --color=always"
  tools:
    name: Get tool-versions
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Parse tool-versions file
        uses: smartcontractkit/tool-versions-to-env-action@aabd5efbaf28005284e846c5cf3a02f2cba2f4c2 # v1.0.8
        id: tool-versions
    outputs:
      golangci-lint-version: ${{ steps.tool-versions.outputs.golangci-lint_version }}
  golangci:
    name: Linting-${{ matrix.project.name }}
    runs-on: ubuntu-latest
    needs: [tools]
    strategy:
      fail-fast: false
      matrix:
        project:
          - name: lib
            path: ./lib/
          - name: gotestloghelper
            path: ./tools/gotestloghelper/
          - name: k8s-test-runner
            path: ./k8s-test-runner/
          - name: testlistgenerator
            path: ./tools/testlistgenerator/
          - name: ecrimagefetcher
            path: ./tools/ecrimagefetcher/
          - name: ghlatestreleasechecker
            path: ./tools/ghlatestreleasechecker/
          - name: asciitable
            path: ./tools/asciitable/
          - name: workflowresultparser
            path: ./tools/workflowresultparser/
    steps:
      - name: Check out Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Go
        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/setup-go@1ada5d85b0de3439a0ba238210d40605b5ed6704 # v2.3.32
        with:
          test_download_vendor_packages_command: cd ${{ matrix.project.path }} && go mod download
          go_mod_path: ${{ matrix.project.path }}go.mod
          cache_key_id: ctf-go-${{ matrix.project.name }}
          cache_restore_only: 'false'
      - name: golangci-lint ${{ needs.tools.outputs.golangci-lint-version }}
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v${{ needs.tools.outputs.golangci-lint-version }}
          args: --out-format checkstyle:golangci-lint-report.xml
          skip-cache: true
          working-directory: ${{ matrix.project.path }}
      - name: Print lint report artifact
        if: always()
        run: test -f ${{ matrix.project.path }}golangci-lint-report.xml || true
      - name: Store lint report artifact
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: golangci-lint-report-${{ matrix.project.name }}
          path: ${{ matrix.project.path }}golangci-lint-report.xml

  vulnerabilities-check:
    name: Check for Vulnerabilities
    runs-on: ubuntu-latest
    needs: [tools]
    steps:
      - name: Check out Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Go
        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/setup-go@1ada5d85b0de3439a0ba238210d40605b5ed6704 # v2.3.32
        with:
          test_download_vendor_packages_command: cd lib && go mod download
          go_mod_path: ./lib/go.mod
          cache_key_id: ctf-go
          cache_restore_only: 'false'
      - name: Write Go List
        working-directory: lib
        run: go list -json -deps ./... > ../go.list
      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@726e338312e68ecdd4b4195765f174d3b3ce1533 # v1.0.3

  asdf-install:
    name: Install ASDF Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4.0.0

  helmlint:
    name: Lint Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Without this parameter, the merged commit that CI produces will make it so that ct will
          # not detect a diff even if one exists
          fetch-depth: 0
      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0
      - name: Add helm chart repo
        run: helm repo add chainlink-qa https://raw.githubusercontent.com/smartcontractkit/qa-charts/gh-pages/
      - name: Run chart-testing (lint)
        run: ct lint --config ${{ github.workspace }}/.github/configs/ct.yaml

  actionlint:
    name: Validate GitHub Action Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run actionlint
        uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281 # v1.65.2

  sonarqube:
    name: SonarQube Analysis
    needs: [golangci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # fetches all history for all tags and branches to provide more metadata for sonar reports
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@8c71dc039c2dd71d3821e89a2b58ecc7fee6ced9 # v5.3.0
        with:
          args: >
            -Dsonar.go.golangci-lint.reportPaths=golangci-lint-report/golangci-lint-report.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
