name: (all packages) Static Analysis
on:
  push:
    branches: [main]
  schedule:
    - cron: '23 19 * * 4'
jobs:
  codeQL:
    name: CodeQL Checks
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Initialize CodeQL
        uses: github/codeql-action/init@28deaeda66b76a05916b6923827895f2b14ab387 # v3.28.16
        with:
          languages: go
      - name: Autobuild
        uses: github/codeql-action/autobuild@28deaeda66b76a05916b6923827895f2b14ab387 # v3.28.16
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@28deaeda66b76a05916b6923827895f2b14ab387 # v3.28.16
