name: (all packages) Unit tests
on:
  push:
    tags:
      - v*
  pull_request:
jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        project:
          - name: lib
            path: ./lib/
          - name: gotestloghelper
            path: ./tools/gotestloghelper/
          - name: testlistgenerator
            path: ./tools/testlistgenerator/
          - name: ecrimagefetcher
            path: ./tools/ecrimagefetcher/
          - name: ghlatestreleasechecker
            path: ./tools/ghlatestreleasechecker/
          - name: asciitable
            path: ./tools/asciitable/
          - name: flakeguard
            path: ./tools/flakeguard/            
          - name: workflowresultparser
            path: ./tools/workflowresultparser/
    runs-on: ubuntu-latest
    name: ${{ matrix.project.name }} unit tests
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install gotestloghelper
        run: cd lib && make gotestloghelper_build
      - name: Install Nix
        uses: cachix/install-nix-action@fc6e360bedc9ee72d75e701397f0bb30dce77568 # v31.5.2
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Load Nix
        run: |
          nix develop -c sh -c "cd ${{ matrix.project.path }} && \
          go mod download"
      - name: Run Tests
        run: |
          PATH=$PATH:$(go env GOPATH)/bin
          export PATH
          set -euo pipefail
          # disabled, because we want to use a multiline output of go list command
          # shellcheck disable=SC2046
          nix develop -c sh -c "cd ${{ matrix.project.path }} && \
            make test_unit"
      - name: Publish Artifacts
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: test-logs
          path: /tmp/gotest.log
