name: WASP Lint
on:
  push:
permissions:
  contents: read
jobs:
  golangci:
    defaults:
      run:
        working-directory: wasp
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'wasp/**'
      - uses: cachix/install-nix-action@56a7bb7b56d9a92d4fd1bc05758de7eea4a370a8 # v31.6.0
        if: steps.changes.outputs.src == 'true'
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run lint
        if: steps.changes.outputs.src == 'true'
        run: |-
          nix develop -c make lint
